apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-connector
  labels:
    app: github-connector
spec:
  selector:
    matchLabels:
      app: github-connector
  template:
    metadata:
      labels:
        app: github-connector
    spec:
      containers:
       - name: github-connector
         image:  ${{ secrets.DOCKER_USERNAME }}/github-connector:vyk3cHAMbsz8BBi2DuZT3
         imagePullPolicy: Always
         env:
          - name: GRPC_PORT
            value: ""
          - name: REST_PORT
            value: ""
         ports:
          - containerPort: 8080
      imagePullSecrets:
          - name: virtuanregsecrets
