// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.1
// source: pub.proto

package pub

import (
	_ "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Createrepodata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Createdat         string `protobuf:"bytes,2,opt,name=createdat,proto3" json:"createdat,omitempty"`
	Updatedat         string `protobuf:"bytes,3,opt,name=updatedat,proto3" json:"updatedat,omitempty"`
	Deletedat         string `protobuf:"bytes,4,opt,name=deletedat,proto3" json:"deletedat,omitempty"`
	Name              string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Autoinit          bool   `protobuf:"varint,6,opt,name=autoinit,proto3" json:"autoinit,omitempty"`
	Private           bool   `protobuf:"varint,7,opt,name=private,proto3" json:"private,omitempty"`
	Gitignoretemplate string `protobuf:"bytes,8,opt,name=gitignoretemplate,proto3" json:"gitignoretemplate,omitempty"`
}

func (x *Createrepodata) Reset() {
	*x = Createrepodata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Createrepodata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Createrepodata) ProtoMessage() {}

func (x *Createrepodata) ProtoReflect() protoreflect.Message {
	mi := &file_pub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Createrepodata.ProtoReflect.Descriptor instead.
func (*Createrepodata) Descriptor() ([]byte, []int) {
	return file_pub_proto_rawDescGZIP(), []int{0}
}

func (x *Createrepodata) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Createrepodata) GetCreatedat() string {
	if x != nil {
		return x.Createdat
	}
	return ""
}

func (x *Createrepodata) GetUpdatedat() string {
	if x != nil {
		return x.Updatedat
	}
	return ""
}

func (x *Createrepodata) GetDeletedat() string {
	if x != nil {
		return x.Deletedat
	}
	return ""
}

func (x *Createrepodata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Createrepodata) GetAutoinit() bool {
	if x != nil {
		return x.Autoinit
	}
	return false
}

func (x *Createrepodata) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *Createrepodata) GetGitignoretemplate() string {
	if x != nil {
		return x.Gitignoretemplate
	}
	return ""
}

type Requestdata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Createdat      string `protobuf:"bytes,2,opt,name=createdat,proto3" json:"createdat,omitempty"`
	Updatedat      string `protobuf:"bytes,3,opt,name=updatedat,proto3" json:"updatedat,omitempty"`
	Deletedat      string `protobuf:"bytes,4,opt,name=deletedat,proto3" json:"deletedat,omitempty"`
	Token          string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Operation      string `protobuf:"bytes,6,opt,name=operation,proto3" json:"operation,omitempty"`
	Gitrepoowner   string `protobuf:"bytes,7,opt,name=gitrepoowner,proto3" json:"gitrepoowner,omitempty"`
	Repotodelete   string `protobuf:"bytes,8,opt,name=repotodelete,proto3" json:"repotodelete,omitempty"`
	Repotocommit   string `protobuf:"bytes,9,opt,name=repotocommit,proto3" json:"repotocommit,omitempty"`
	Branchtocommit string `protobuf:"bytes,10,opt,name=branchtocommit,proto3" json:"branchtocommit,omitempty"`
}

func (x *Requestdata) Reset() {
	*x = Requestdata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Requestdata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requestdata) ProtoMessage() {}

func (x *Requestdata) ProtoReflect() protoreflect.Message {
	mi := &file_pub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requestdata.ProtoReflect.Descriptor instead.
func (*Requestdata) Descriptor() ([]byte, []int) {
	return file_pub_proto_rawDescGZIP(), []int{1}
}

func (x *Requestdata) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Requestdata) GetCreatedat() string {
	if x != nil {
		return x.Createdat
	}
	return ""
}

func (x *Requestdata) GetUpdatedat() string {
	if x != nil {
		return x.Updatedat
	}
	return ""
}

func (x *Requestdata) GetDeletedat() string {
	if x != nil {
		return x.Deletedat
	}
	return ""
}

func (x *Requestdata) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Requestdata) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Requestdata) GetGitrepoowner() string {
	if x != nil {
		return x.Gitrepoowner
	}
	return ""
}

func (x *Requestdata) GetRepotodelete() string {
	if x != nil {
		return x.Repotodelete
	}
	return ""
}

func (x *Requestdata) GetRepotocommit() string {
	if x != nil {
		return x.Repotocommit
	}
	return ""
}

func (x *Requestdata) GetBranchtocommit() string {
	if x != nil {
		return x.Branchtocommit
	}
	return ""
}

type RequestDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RequestDto) Reset() {
	*x = RequestDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDto) ProtoMessage() {}

func (x *RequestDto) ProtoReflect() protoreflect.Message {
	mi := &file_pub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDto.ProtoReflect.Descriptor instead.
func (*RequestDto) Descriptor() ([]byte, []int) {
	return file_pub_proto_rawDescGZIP(), []int{2}
}

func (x *RequestDto) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ResponseDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResponseDto) Reset() {
	*x = ResponseDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDto) ProtoMessage() {}

func (x *ResponseDto) ProtoReflect() protoreflect.Message {
	mi := &file_pub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDto.ProtoReflect.Descriptor instead.
func (*ResponseDto) Descriptor() ([]byte, []int) {
	return file_pub_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseDto) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SidecarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestDto *RequestDto `protobuf:"bytes,1,opt,name=RequestDto,proto3" json:"RequestDto,omitempty"`
}

func (x *SidecarRequest) Reset() {
	*x = SidecarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SidecarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidecarRequest) ProtoMessage() {}

func (x *SidecarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidecarRequest.ProtoReflect.Descriptor instead.
func (*SidecarRequest) Descriptor() ([]byte, []int) {
	return file_pub_proto_rawDescGZIP(), []int{4}
}

func (x *SidecarRequest) GetRequestDto() *RequestDto {
	if x != nil {
		return x.RequestDto
	}
	return nil
}

var File_pub_proto protoreflect.FileDescriptor

var file_pub_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x75, 0x62,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf2, 0x01,
	0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x72, 0x65, 0x70, 0x6f, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x61, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x75, 0x74, 0x6f, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x61, 0x75, 0x74, 0x6f, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x67, 0x69, 0x74, 0x69, 0x67, 0x6e, 0x6f, 0x72,
	0x65, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x11, 0x67, 0x69, 0x74, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x22, 0xbf, 0x02, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x61, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x61, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x67, 0x69, 0x74, 0x72, 0x65, 0x70, 0x6f, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x69, 0x74, 0x72, 0x65, 0x70, 0x6f, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x74, 0x6f, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6f,
	0x74, 0x6f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x70, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x74, 0x6f, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44,
	0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x0e, 0x53, 0x69, 0x64,
	0x65, 0x63, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x74, 0x6f,
	0x52, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x74, 0x6f, 0x32, 0x3d, 0x0a, 0x07,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x53, 0x69, 0x64, 0x65, 0x63,
	0x61, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x2f, 0x3b, 0x70, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pub_proto_rawDescOnce sync.Once
	file_pub_proto_rawDescData = file_pub_proto_rawDesc
)

func file_pub_proto_rawDescGZIP() []byte {
	file_pub_proto_rawDescOnce.Do(func() {
		file_pub_proto_rawDescData = protoimpl.X.CompressGZIP(file_pub_proto_rawDescData)
	})
	return file_pub_proto_rawDescData
}

var file_pub_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pub_proto_goTypes = []interface{}{
	(*Createrepodata)(nil), // 0: pub.Createrepodata
	(*Requestdata)(nil),    // 1: pub.Requestdata
	(*RequestDto)(nil),     // 2: pub.RequestDto
	(*ResponseDto)(nil),    // 3: pub.ResponseDto
	(*SidecarRequest)(nil), // 4: pub.SidecarRequest
}
var file_pub_proto_depIdxs = []int32{
	2, // 0: pub.SidecarRequest.RequestDto:type_name -> pub.RequestDto
	4, // 1: pub.Service.Sidecar:input_type -> pub.SidecarRequest
	3, // 2: pub.Service.Sidecar:output_type -> pub.ResponseDto
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pub_proto_init() }
func file_pub_proto_init() {
	if File_pub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Createrepodata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Requestdata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pub_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SidecarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pub_proto_goTypes,
		DependencyIndexes: file_pub_proto_depIdxs,
		MessageInfos:      file_pub_proto_msgTypes,
	}.Build()
	File_pub_proto = out.File
	file_pub_proto_rawDesc = nil
	file_pub_proto_goTypes = nil
	file_pub_proto_depIdxs = nil
}
