name: github-connector
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: generate swagger
      run: |
       # Dowloading the swagger client
       wget https://github.com/swaggo/swag/releases/download/v1.7.0/swag_1.7.0_Linux_x86_64.tar.gz
       tar -xvf swag_1.7.0_Linux_x86_64.tar.gz
       ./swag init
       rm swag
       rm swag_1.7.0_Linux_x86_64.tar.gz

    - name: build and deploy
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: ${{ secrets.DOCKER_USERNAME }}/github-connector
          tags: vyk3cHAMbsz8BBi2DuZT3
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
